### ISSUE TITLE
BSOD crash at program exit with 4 PDV channels

### ISSUE THREAD

**Issue by john-judge** [john-judge/PhotoZ_upgrades#7]
From Meyer, 12/21/2020:

One problem I was hoping to solve with studio running on the rig computer was a crash that occurs when I exit photoz after opening more than one pdv channel.

In Camera.cpp I change this number to 4 in Camera::open_channel() (lines 101-117). This ultimately will be necessary because the camera uses 4 channels simultaneously and I have so far been trying to trouble shoot the program using just one pdv channel.

When I run the program with 4 pdv channels open the program crashes upon exiting. I thought that when I had studio running on the computer I would get a debugging message that would locate the problem. Instead I get a ‘blue screen’ crash. When I put in cout commands in various locations I could see that the crash occurred after line 129 of MainController.cpp after the call to exit(0).

On 12/23/2020, Meyer:

The program starts up but even when no actions are performed from the user interface and you exit either by using the exit button or clicking the x in the upper right corner you get a blue screen crash with the message “process has locked pages”. This does not happen when running on my office computer, which of course is not connected to a camera.

I am starting to think the crash upon exit is not a C++ coding issue. As I mentioned, my office computer does not crash and I thought the difference was that there is no camera connected to my office computer.

However, I simply turned off the power to the rig computer and the problem persisted.

So the problem is likely in the computer environment of my rig computer which is different on my office computer.

**Comment by john-judge** [comment]
Does this mean that when you prevent the rig computer from connecting to the cameras, the crash problem persists?

Suggestions I gave to Meyer:
* We're generally following the recommendations in DV-2K-CamInit - Chun.txt. The driver should never cause blue-screen crashes, and it may be good to report this to PDV once we've narrowed down the issue and are sure about what causes the crash. <I looked at PDV changelog. There were some mentions of Windows 7 and previous OS bluescreens, but nothing suspicious in recent versions>
* We call pdv_open_channel with the channel = 0 argument fixed for all four calls. According to this documentation, the channel should probably range over 0,1,2,3.
* We currently are just discarding the return value of pdv_close. According to PDV documentation, it will return 0 if successful, and -1 if unsuccessful. Ideally, we should report to the user and/or reattempt the channel shutdown if it's unsuccessful. 
* Add a cout print statement in the branch where pdv_open_channel is called, printing whether the channel successfully opened.
* Print statements for successful pdv_close might not catch in time for you to review before the computer shuts down. So, to determine whether the pdv_close is successful and whether the Camera destructor is actually getting called as I would expect, you can set a breakpoint in Visual Studio before launching PhotoZ with the VS debugger.  <gave instructions on breakpoints in case Meyer needed>

**Comment by john-judge** [comment]
From Meyer, 12/24:

I found that cout would produce the pdv pointers even with the camera off. If must be able to open the channels on the card in the computer.

So it still can be a coding problem. One possible source is a redundancy I just found.

In Camera.cpp the module Camera:open_channel() (lines 102-119) is redundant with Camera::init_cam (lines 129-176).

Open_channel was from the old version of photoz that runs lilJoe. I added init_cam according to instructions from Chun. But they both call pdv_open_channel.

I suspect the values for unit and channel in open_channel is not quite right and that is causing the problem. When I remove all calls to Camera::open_channel and use init.cam instead I am able to start working with 4 pdv channels (I think).

**Comment by chuangshizhiqiang** [comment]
Can you show me the BSOD dump file?

**Comment by john-judge** [comment]
@chuangshizhiqiang Thanks for your interest. I've asked Meyer for the .dmp file from the machine with the camera hardware -- will post here when I get it.

As far as I know, the BSOD is not reproducible without the camera.

Meyer isn't a Git user and has introduced recent changes that aren't tracked in this repository. I suspect there are some abuses of the PDV driver lib that need to be addressed.

**Comment by john-judge** [comment]
As suspected, PDV is implicated in the stack trace, and the deferred procedure call (DPC) suggests unresponsive hardware.

Meyer was able to apparently resolve the issue by removing redundancy of camera open-channel calls and using the proper parameters for unit and and channel.

[Crash .dmp file](https://github.com/john-judge/PhotoZ_upgrades/blob/main/documentation/crash_dumps/122620-15390-01.dmp)

```
ADDITIONAL_XML: 1

OS_BUILD_LAYERS: 1

BUGCHECK_CODE:  133

BUGCHECK_P1: 1

BUGCHECK_P2: 1e00

BUGCHECK_P3: fffff802179f6348

BUGCHECK_P4: 0

DPC_TIMEOUT_TYPE:  DPC_QUEUE_EXECUTION_TIMEOUT_EXCEEDED

TRAP_FRAME:  fffff80219a40730 -- (.trap 0xfffff80219a40730)
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect.
rax=00000000ca2a1000 rbx=0000000000000000 rcx=ffffb1807c29e014
rdx=0000000004030014 rsi=0000000000000000 rdi=0000000000000000
rip=fffff80efba0927c rsp=fffff80219a408c8 rbp=fffff80219a40d70
 r8=00000000ca2a1000  r9=0000000000000000 r10=ffffd3876a7c55e0
r11=ffffd3876d0242f0 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei ng nz na po nc
pdvwdf+0x927c:
fffff80e`fba0927c c3              ret
Resetting default scope

BLACKBOXBSD: 1 (!blackboxbsd)


CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  ScriptedSandbox

DPC_STACK_BASE:  FFFFF80219A40FB0

STACK_TEXT:  
fffff802`19a47bc8 fffff802`177d5d63     : 00000000`00000133 00000000`00000001 00000000`00001e00 fffff802`179f6348 : nt!KeBugCheckEx
fffff802`19a47bd0 fffff802`176b9099     : 00002aff`03abb877 fffff802`16426180 00000000`00008cc6 00000000`00000002 : nt!KeAccumulateTicks+0x11a563
fffff802`19a47c30 fffff802`17ea2676     : 00002aff`03aba872 00000000`00000000 fffff802`19a40730 fffff802`17ef2460 : nt!KeClockInterruptNotify+0x599
fffff802`19a47f40 fffff802`1766ea45     : fffff802`17ef23b0 fffff802`1778e100 ffffb180`7c795008 fffff802`19a40a00 : hal!HalpTimerClockInterrupt+0x56
fffff802`19a47f70 fffff802`1778e4ba     : fffff802`19a407b0 fffff802`17ef23b0 00000000`00000000 fffff802`19a40ef0 : nt!KiCallInterruptServiceRoutine+0xa5
fffff802`19a47fb0 fffff802`1778e9c7     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiInterruptSubDispatchNoLockNoEtw+0xea
fffff802`19a40730 fffff80e`fba0927c     : fffff80e`fba0b29f ffffb180`7c29e014 fffff80e`fba0a4a5 ffffb180`7c29e000 : nt!KiInterruptDispatchNoLockNoEtw+0x37
fffff802`19a408c8 fffff80e`fba0b29f     : ffffb180`7c29e014 fffff80e`fba0a4a5 ffffb180`7c29e000 fffff80e`ca2a1000 : pdvwdf+0x927c
fffff802`19a408d0 ffffb180`7c29e014     : fffff80e`fba0a4a5 ffffb180`7c29e000 fffff80e`ca2a1000 00000017`6a7c4cff : pdvwdf+0xb29f
fffff802`19a408d8 fffff80e`fba0a4a5     : ffffb180`7c29e000 fffff80e`ca2a1000 00000017`6a7c4cff 00000017`fba0b501 : 0xffffb180`7c29e014
fffff802`19a408e0 ffffb180`7c29e000     : fffff80e`ca2a1000 00000017`6a7c4cff 00000017`fba0b501 ffffffff`6d024204 : pdvwdf+0xa4a5
fffff802`19a408e8 fffff80e`ca2a1000     : 00000017`6a7c4cff 00000017`fba0b501 ffffffff`6d024204 ffff000d`00000003 : 0xffffb180`7c29e000
fffff802`19a408f0 00000017`6a7c4cff     : 00000017`fba0b501 ffffffff`6d024204 ffff000d`00000003 00000014`00000004 : 0xfffff80e`ca2a1000
fffff802`19a408f8 00000017`fba0b501     : ffffffff`6d024204 ffff000d`00000003 00000014`00000004 ffff0014`fba0b204 : 0x00000017`6a7c4cff
fffff802`19a40900 ffffffff`6d024204     : ffff000d`00000003 00000014`00000004 ffff0014`fba0b204 ca2a1000`7c290000 : 0x00000017`fba0b501
fffff802`19a40908 ffff000d`00000003     : 00000014`00000004 ffff0014`fba0b204 ca2a1000`7c290000 fffff80e`fba0a400 : 0xffffffff`6d024204
fffff802`19a40910 00000014`00000004     : ffff0014`fba0b204 ca2a1000`7c290000 fffff80e`fba0a400 00000000`00000004 : 0xffff000d`00000003
fffff802`19a40918 ffff0014`fba0b204     : ca2a1000`7c290000 fffff80e`fba0a400 00000000`00000004 00000000`00000000 : 0x00000014`00000004
fffff802`19a40920 ca2a1000`7c290000     : fffff80e`fba0a400 00000000`00000004 00000000`00000000 ffffb180`7c530000 : 0xffff0014`fba0b204
fffff802`19a40928 fffff80e`fba0a400     : 00000000`00000004 00000000`00000000 ffffb180`7c530000 fffff804`31000003 : 0xca2a1000`7c290000
fffff802`19a40930 00000000`00000004     : 00000000`00000000 ffffb180`7c530000 fffff804`31000003 71c30010`6a7c4c04 : pdvwdf+0xa400
fffff802`19a40938 00000000`00000000     : ffffb180`7c530000 fffff804`31000003 71c30010`6a7c4c04 ffff00cc`fba14e03 : 0x4


SYMBOL_NAME:  pdvwdf+927c

MODULE_NAME: pdvwdf

IMAGE_NAME:  pdvwdf.sys

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  927c

FAILURE_BUCKET_ID:  0x133_ISR_pdvwdf!unknown_function

OS_VERSION:  10.0.15063.0

BUILDLAB_STR:  rs2_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {161eff92-5caf-c472-dc3f-291decf605eb}

Followup:     MachineOwner
---------
```




```
start             end                 module name
fffff80e`fba00000 fffff80e`fba41000   pdvwdf   T (no symbols)           
    Loaded symbol image file: pdvwdf.sys
    Image path: \SystemRoot\System32\drivers\pdvwdf.sys
    Image name: pdvwdf.sys
```

**Comment by chuangshizhiqiang** [comment]
> @chuangshizhiqiang Thanks for your interest. I've asked Meyer for the .dmp file from the machine with the camera hardware -- will post here when I get it.
> 
> As far as I know, the BSOD is not reproducible without the camera.
> 
> Meyer isn't a Git user and has introduced recent changes that aren't tracked in this repository. I suspect there are some abuses of the PDV driver lib that need to be addressed.

You are right, I don't hava pdvwdf.sys.......
